"""initial_schema

Revision ID: 905078751efe
Revises: 
Create Date: 2026-05-15 00:34:00.426352
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '905078751efe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('terms_url', sa.String(length=2048), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_contracts_company_id'), 'agent_contracts', ['company_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('commission_schemes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_schemes_company_id'), 'commission_schemes', ['company_id'], unique=False)
    op.create_index(op.f('ix_commission_schemes_effective_from'), 'commission_schemes', ['effective_from'], unique=False)
    op.create_index(op.f('ix_commission_schemes_effective_to'), 'commission_schemes', ['effective_to'], unique=False)
    op.create_index(op.f('ix_commission_schemes_status'), 'commission_schemes', ['status'], unique=False)
    op.create_table('company_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_contacts_company_id'), 'company_contacts', ['company_id'], unique=False)
    op.create_table('payment_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_plans_code'), 'payment_plans', ['code'], unique=False)
    op.create_index(op.f('ix_payment_plans_company_id'), 'payment_plans', ['company_id'], unique=False)
    op.create_index(op.f('ix_payment_plans_effective_from'), 'payment_plans', ['effective_from'], unique=False)
    op.create_index(op.f('ix_payment_plans_effective_to'), 'payment_plans', ['effective_to'], unique=False)
    op.create_index(op.f('ix_payment_plans_status'), 'payment_plans', ['status'], unique=False)
    op.create_table('pricing_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('storage_url', sa.String(length=2048), nullable=False),
    sa.Column('ocr_status', sa.String(length=32), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_documents_company_id'), 'pricing_documents', ['company_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'slug', name='uq_projects_company_slug')
    )
    op.create_index(op.f('ix_projects_area'), 'projects', ['area'], unique=False)
    op.create_index(op.f('ix_projects_city'), 'projects', ['city'], unique=False)
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_table('sales_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_channels_company_id'), 'sales_channels', ['company_id'], unique=False)
    op.create_table('unit_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('default_area_sqm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('finish_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_types_code'), 'unit_types', ['code'], unique=False)
    op.create_index(op.f('ix_unit_types_company_id'), 'unit_types', ['company_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_project_id'), 'blocks', ['project_id'], unique=False)
    op.create_table('commission_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commission_scheme_id', sa.UUID(), nullable=False),
    sa.Column('sales_channel', sa.String(length=64), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commission_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commission_scheme_id'], ['commission_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_rules_commission_scheme_id'), 'commission_rules', ['commission_scheme_id'], unique=False)
    op.create_index(op.f('ix_commission_rules_sales_channel'), 'commission_rules', ['sales_channel'], unique=False)
    op.create_table('payment_plan_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_plan_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('milestone_name', sa.String(length=255), nullable=True),
    sa.Column('due_after_days', sa.Integer(), nullable=True),
    sa.Column('due_after_months', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_plan_steps_payment_plan_id'), 'payment_plan_steps', ['payment_plan_id'], unique=False)
    op.create_table('pricing_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('pricing_document_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('includes_vat', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pricing_document_id'], ['pricing_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_versions_company_id'), 'pricing_versions', ['company_id'], unique=False)
    op.create_index(op.f('ix_pricing_versions_effective_from'), 'pricing_versions', ['effective_from'], unique=False)
    op.create_index(op.f('ix_pricing_versions_effective_to'), 'pricing_versions', ['effective_to'], unique=False)
    op.create_index(op.f('ix_pricing_versions_status'), 'pricing_versions', ['status'], unique=False)
    op.create_table('discount_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pricing_version_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pricing_version_id'], ['pricing_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_rules_pricing_version_id'), 'discount_rules', ['pricing_version_id'], unique=False)
    op.create_table('price_history_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pricing_version_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pricing_version_id'], ['pricing_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_events_pricing_version_id'), 'price_history_events', ['pricing_version_id'], unique=False)
    op.create_table('price_table_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pricing_version_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('floor_band', sa.String(length=64), nullable=True),
    sa.Column('unit_type_code', sa.String(length=64), nullable=True),
    sa.Column('finish_type', sa.String(length=64), nullable=True),
    sa.Column('construction_state', sa.String(length=64), nullable=True),
    sa.Column('price_per_sqm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fixed_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pricing_version_id'], ['pricing_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_table_rows_block_id'), 'price_table_rows', ['block_id'], unique=False)
    op.create_index(op.f('ix_price_table_rows_pricing_version_id'), 'price_table_rows', ['pricing_version_id'], unique=False)
    op.create_index(op.f('ix_price_table_rows_project_id'), 'price_table_rows', ['project_id'], unique=False)
    op.create_table('property_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('unit_type_id', sa.UUID(), nullable=False),
    sa.Column('unit_number', sa.String(length=64), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('orientation', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_units_block_id'), 'property_units', ['block_id'], unique=False)
    op.create_index(op.f('ix_property_units_floor_number'), 'property_units', ['floor_number'], unique=False)
    op.create_index(op.f('ix_property_units_status'), 'property_units', ['status'], unique=False)
    op.create_index(op.f('ix_property_units_unit_type_id'), 'property_units', ['unit_type_id'], unique=False)
    op.create_table('property_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_listings_area'), 'property_listings', ['area'], unique=False)
    op.create_index(op.f('ix_property_listings_city'), 'property_listings', ['city'], unique=False)
    op.create_index(op.f('ix_property_listings_is_public'), 'property_listings', ['is_public'], unique=False)
    op.create_index(op.f('ix_property_listings_slug'), 'property_listings', ['slug'], unique=True)
    op.create_index(op.f('ix_property_listings_unit_id'), 'property_listings', ['unit_id'], unique=False)
    op.create_table('unit_price_quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('pricing_version_id', sa.UUID(), nullable=True),
    sa.Column('payment_plan_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('down_payment_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('calculation_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pricing_version_id'], ['pricing_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_price_quotes_unit_id'), 'unit_price_quotes', ['unit_id'], unique=False)
    op.create_table('unit_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_status_history_unit_id'), 'unit_status_history', ['unit_id'], unique=False)
    op.create_table('commission_estimates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_price_quote_id', sa.UUID(), nullable=False),
    sa.Column('commission_scheme_id', sa.UUID(), nullable=True),
    sa.Column('commission_rule_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commission_rule_id'], ['commission_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['commission_scheme_id'], ['commission_schemes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_price_quote_id'], ['unit_price_quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_estimates_unit_price_quote_id'), 'commission_estimates', ['unit_price_quote_id'], unique=False)
    op.create_table('installment_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_price_quote_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_price_quote_id'], ['unit_price_quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_schedules_unit_price_quote_id'), 'installment_schedules', ['unit_price_quote_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['property_listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['unit_price_quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_listing_id'), 'leads', ['listing_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_unit_id'), 'leads', ['unit_id'], unique=False)
    op.create_table('property_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('public_id', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['property_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_images_listing_id'), 'property_images', ['listing_id'], unique=False)
    op.create_table('property_view_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['property_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_view_events_listing_id'), 'property_view_events', ['listing_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['unit_price_quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_quote_id'), 'reservations', ['quote_id'], unique=False)
    op.create_index(op.f('ix_reservations_unit_id'), 'reservations', ['unit_id'], unique=False)
    op.create_table('installment_schedule_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installment_schedule_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('due_type', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['installment_schedule_id'], ['installment_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_schedule_items_installment_schedule_id'), 'installment_schedule_items', ['installment_schedule_id'], unique=False)
    op.create_table('lead_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_events_lead_id'), 'lead_events', ['lead_id'], unique=False)
    op.create_table('lead_quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['unit_price_quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_quotes_lead_id'), 'lead_quotes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_quotes_quote_id'), 'lead_quotes', ['quote_id'], unique=False)
    op.create_table('sales_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('contract_number', sa.String(length=64), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('locked_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['unit_price_quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_contracts_contract_number'), 'sales_contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_sales_contracts_quote_id'), 'sales_contracts', ['quote_id'], unique=False)
    op.create_index(op.f('ix_sales_contracts_status'), 'sales_contracts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_contracts_status'), table_name='sales_contracts')
    op.drop_index(op.f('ix_sales_contracts_quote_id'), table_name='sales_contracts')
    op.drop_index(op.f('ix_sales_contracts_contract_number'), table_name='sales_contracts')
    op.drop_table('sales_contracts')
    op.drop_index(op.f('ix_lead_quotes_quote_id'), table_name='lead_quotes')
    op.drop_index(op.f('ix_lead_quotes_lead_id'), table_name='lead_quotes')
    op.drop_table('lead_quotes')
    op.drop_index(op.f('ix_lead_events_lead_id'), table_name='lead_events')
    op.drop_table('lead_events')
    op.drop_index(op.f('ix_installment_schedule_items_installment_schedule_id'), table_name='installment_schedule_items')
    op.drop_table('installment_schedule_items')
    op.drop_index(op.f('ix_reservations_unit_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_quote_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_property_view_events_listing_id'), table_name='property_view_events')
    op.drop_table('property_view_events')
    op.drop_index(op.f('ix_property_images_listing_id'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_leads_unit_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_listing_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_installment_schedules_unit_price_quote_id'), table_name='installment_schedules')
    op.drop_table('installment_schedules')
    op.drop_index(op.f('ix_commission_estimates_unit_price_quote_id'), table_name='commission_estimates')
    op.drop_table('commission_estimates')
    op.drop_index(op.f('ix_unit_status_history_unit_id'), table_name='unit_status_history')
    op.drop_table('unit_status_history')
    op.drop_index(op.f('ix_unit_price_quotes_unit_id'), table_name='unit_price_quotes')
    op.drop_table('unit_price_quotes')
    op.drop_index(op.f('ix_property_listings_unit_id'), table_name='property_listings')
    op.drop_index(op.f('ix_property_listings_slug'), table_name='property_listings')
    op.drop_index(op.f('ix_property_listings_is_public'), table_name='property_listings')
    op.drop_index(op.f('ix_property_listings_city'), table_name='property_listings')
    op.drop_index(op.f('ix_property_listings_area'), table_name='property_listings')
    op.drop_table('property_listings')
    op.drop_index(op.f('ix_property_units_unit_type_id'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_status'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_floor_number'), table_name='property_units')
    op.drop_index(op.f('ix_property_units_block_id'), table_name='property_units')
    op.drop_table('property_units')
    op.drop_index(op.f('ix_price_table_rows_project_id'), table_name='price_table_rows')
    op.drop_index(op.f('ix_price_table_rows_pricing_version_id'), table_name='price_table_rows')
    op.drop_index(op.f('ix_price_table_rows_block_id'), table_name='price_table_rows')
    op.drop_table('price_table_rows')
    op.drop_index(op.f('ix_price_history_events_pricing_version_id'), table_name='price_history_events')
    op.drop_table('price_history_events')
    op.drop_index(op.f('ix_discount_rules_pricing_version_id'), table_name='discount_rules')
    op.drop_table('discount_rules')
    op.drop_index(op.f('ix_pricing_versions_status'), table_name='pricing_versions')
    op.drop_index(op.f('ix_pricing_versions_effective_to'), table_name='pricing_versions')
    op.drop_index(op.f('ix_pricing_versions_effective_from'), table_name='pricing_versions')
    op.drop_index(op.f('ix_pricing_versions_company_id'), table_name='pricing_versions')
    op.drop_table('pricing_versions')
    op.drop_index(op.f('ix_payment_plan_steps_payment_plan_id'), table_name='payment_plan_steps')
    op.drop_table('payment_plan_steps')
    op.drop_index(op.f('ix_commission_rules_sales_channel'), table_name='commission_rules')
    op.drop_index(op.f('ix_commission_rules_commission_scheme_id'), table_name='commission_rules')
    op.drop_table('commission_rules')
    op.drop_index(op.f('ix_blocks_project_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_unit_types_company_id'), table_name='unit_types')
    op.drop_index(op.f('ix_unit_types_code'), table_name='unit_types')
    op.drop_table('unit_types')
    op.drop_index(op.f('ix_sales_channels_company_id'), table_name='sales_channels')
    op.drop_table('sales_channels')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_city'), table_name='projects')
    op.drop_index(op.f('ix_projects_area'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_pricing_documents_company_id'), table_name='pricing_documents')
    op.drop_table('pricing_documents')
    op.drop_index(op.f('ix_payment_plans_status'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_effective_to'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_effective_from'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_company_id'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_code'), table_name='payment_plans')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_company_contacts_company_id'), table_name='company_contacts')
    op.drop_table('company_contacts')
    op.drop_index(op.f('ix_commission_schemes_status'), table_name='commission_schemes')
    op.drop_index(op.f('ix_commission_schemes_effective_to'), table_name='commission_schemes')
    op.drop_index(op.f('ix_commission_schemes_effective_from'), table_name='commission_schemes')
    op.drop_index(op.f('ix_commission_schemes_company_id'), table_name='commission_schemes')
    op.drop_table('commission_schemes')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agent_contracts_company_id'), table_name='agent_contracts')
    op.drop_table('agent_contracts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
